[package]
name = "datafmts"
version = "0.1.0"
edition = "2021"
description = "modular no_std library for serializing/deserializing multiple file format"
license = "MIT"

[features]
default = ["derive"]
derive = ["dep:datafmts_derive"]

[dependencies]
datafmts_derive = { version = "0.1.0", path = "../datafmts_derive", optional = true }
